# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotlogger < Formula
  desc "Workflow-aware developer operations terminal"
  homepage "https://github.com/EfeDurmaz16/jot-logger"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.4.0/jotlogger_darwin_amd64.tar.gz"
      sha256 "c2b5838745257ff185f49f1a4f61f05362ee206e25f60631555cc0794d26a5a1"

      define_method(:install) do
        bin.install "jotlogger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.4.0/jotlogger_darwin_arm64.tar.gz"
      sha256 "ee1a9730a439e20886b0ca06f9b6037ecc9d4bf6b2648c7de06ec22515348152"

      define_method(:install) do
        bin.install "jotlogger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.4.0/jotlogger_linux_amd64.tar.gz"
      sha256 "30511a7a0f2899db45ede0fea57e214d580b9f80c529c76665e7396e87fb72b0"
      define_method(:install) do
        bin.install "jotlogger"
      end
    end
  end

  test do
    system "#{bin}/jotlogger", "--version"
  end
end
