# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotlogger < Formula
  desc "Workflow-aware developer operations terminal"
  homepage "https://github.com/EfeDurmaz16/jot-logger"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.3.0/jotlogger_darwin_amd64.tar.gz"
      sha256 "944638550d34b410a92c305d83f05df7ca8c3b011d6a8ffba3914ed5d28671da"

      define_method(:install) do
        bin.install "jotlogger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.3.0/jotlogger_darwin_arm64.tar.gz"
      sha256 "0d1a9a077c5d48604162a12b6a623f2a5def664a9f958278ee487f9c69a1b2e8"

      define_method(:install) do
        bin.install "jotlogger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EfeDurmaz16/jot-logger/releases/download/v0.3.0/jotlogger_linux_amd64.tar.gz"
      sha256 "98f8784aacd625a8ec860d3df8a983e97246636a1c8173a81c5941f5d4f581f7"
      define_method(:install) do
        bin.install "jotlogger"
      end
    end
  end

  test do
    system "#{bin}/jotlogger", "--version"
  end
end
