# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sardis < Formula
  desc "CLI for Sardis — Payment OS for the Agent Economy"
  homepage "https://sardis.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EfeDurmaz16/sardis/releases/download/v0.1.0/sardis_darwin_amd64.tar.gz"
      sha256 "daf3b0eafec07c2b6f55e9ee5f4b1c70db643a11a05b1ff29674a7bc48dce231"

      define_method(:install) do
        bin.install "sardis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EfeDurmaz16/sardis/releases/download/v0.1.0/sardis_darwin_arm64.tar.gz"
      sha256 "4987018011687d25d1e4bc770762659bfb2c5c8bdbaa480789589f8e23c31f6d"

      define_method(:install) do
        bin.install "sardis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EfeDurmaz16/sardis/releases/download/v0.1.0/sardis_linux_amd64.tar.gz"
      sha256 "121274be72b9eb65961ea33665d0faabe79434ec1a55cc835a855fab503c051c"
      define_method(:install) do
        bin.install "sardis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EfeDurmaz16/sardis/releases/download/v0.1.0/sardis_linux_arm64.tar.gz"
      sha256 "32d544172601ca890f19239bfc0bcafe61ae1518cb8f0564a1d21700da781666"
      define_method(:install) do
        bin.install "sardis"
      end
    end
  end

  test do
    system "#{bin}/sardis", "--help"
  end
end
